### ISSUE TITLE
[DOCS] Control Tower - CloudTrail new capability

### ISSUE THREAD

**Issue by drewdresser** [aws-samples/aws-secure-environment-accelerator#1021]
**Required Basic Info**
- Accelerator Version:  1.5.3
- Install Type: Clean

**Describe the bug**
In Control Tower section of the documentation, should the ASEA include reference to using Control Tower's new CloudTrail capabilities? What setup should we use - Enabled, or Disabled?

<img width="934" alt="CleanShot 2022-08-02 at 22 24 08@2x" src="https://user-images.githubusercontent.com/3165185/182510770-6f593f21-cef9-438f-8b1c-7d8499a6546c.png">

**Comment by KyleSouthworthGSS** [comment]
Hi, I have tried the Control Tower CloudTrail configuration set to 'Not enabled' and 'Enabled', each resulted in the ASEA phase 4 failing to update LogGroupMetricFilters. I have raised this with AWS as I am also seeing the following error in Control Tower:
"AWS Control Tower failed to delete your account trails completely: AWS Control Tower encountered an error deleting your account trails. Try again later. If this error persists, contact AWS Support."
I think the above is due to the ASEA SCPs but I want AWS to confirm before making any further changes.

**Comment by KyleSouthworthGSS** [comment]
Just had confirmation off AWS support - 

"Further, I would like to inform you that in the recent update [1] of landing zone version (3.0) we no longer create the IAM role aws-controltower-CloudWatchLogsRole and the CloudWatch log group aws-controltower/CloudTrailLogs in each enrolled account. Previously, we created these in each account for its account trail. With organization trails, we only create one in the management account. So the log group aws-controltower/CloudTrailLogs would have been deleted for the member accounts after the CT update."

**Comment by drewdresser** [comment]
Thanks, Kyle. Which "landing zone" are you referring to that has a version
3.0?

**Comment by Brian969** [comment]
- Control Tower updated to version 3 which moved to Organization based CloudTrail rather than account based
- the ASEA example CT config file is no longer valid for Control Tower v3+
- the cloudwatch metric and alarms sections of the example CT config file need to be updated to look more like all the other non-CT example config files (specifically, lines 231-445)
- i.e. `"accounts": ["ALL"]` to `"accounts": ["management"]` and` "default-accounts": ["ALL"]` to `"default-accounts": ["management"]` also - I have not looked, but `"loggroup-name": "aws-controltower/CloudTrailLogs"` needs to be validated as still being the correct name.
- To answer the original question - `What setup should we use - Enabled, or Disabled?` you should select Enabled.

**Comment by KyleSouthworthGSS** [comment]
Thanks @Brian969 this helped me resolve.
