### ISSUE TITLE
[BUG][Functional] CWL_THROTTLING_EXCEPTION on CreateLogStream

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-secure-environment-accelerator#1022]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.5.0
- Install Type: Clean
- Upgrade from version: v1.5.0 to v1.5.3

**Describe the bug**
CodeBuild DeployPrebuilt project phase at the PROVISIONING phase with 'CWL_THROTTLING_EXCEPTION: The maximum request reate permitted by Amazon CloudWatch Logs has been exceeded for your account. Error Message: Rate exceeded'.  The StateMachine fails in Phase0 or Phase1.

CloudWatch Logs show a high number of CreateLogStream API calls from the 'InitialSetup-PipelineStoreOutputsHandler' assumed role. The default account service quota limit is 50/second.

Increasing the quota service limit to 150 resolved the issue. 

**Failure Info**
- What error messages have you identified, if any: 
- What symptoms have you identified, if any:

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
Currently unknown what is causing the issue. This has been detected in 2 different ASEA installations with < 50 AWS Accounts in the Organization.

**Comment by Brian969** [comment]
- Believe this is being caused by the `Store Phase X Outputs` SM step and has nothing to do with Codebuild or PhaseX steps.
- that Lambda currently executes code per region, per account - but all in the management account
- I believe it is likely creating a new stream per account, per region

- i.e.: 
![image](https://user-images.githubusercontent.com/56414362/183305108-55a49ff0-315c-4101-970a-e29083ebbdda.png)

- i.e.: 
![image](https://user-images.githubusercontent.com/56414362/183305137-5345359b-2855-42b3-92d4-15f07b108c98.png)
and
![image](https://user-images.githubusercontent.com/56414362/183305175-5b535e38-f597-4088-9bb1-ea943b0b56b8.png)
...are in different streams...

**Comment by Brian969** [comment]
see Issue#1023
