### ISSUE TITLE
SCP not allowing configuration of development environment

### ISSUE THREAD

**Issue by Omofehintola** [aws-samples/aws-secure-environment-accelerator#655]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.2.6a
- Install Type: Clean 
- Upgrade from version: N/A

**Describe the bug**
(A clear and concise description of what the bug is.)
SEA deployment was complete but all attempts to switch roles into the developer account as an admin keeps failing as I was denied permission by the SCP. Attempts to detach any of the SCPs for the Developer account or Dev OU by re-running the SEA failed to allow such a switch. Attempts to move account to another OU gives the same results. All efforts to adjust the config file to allow access to the developer account keeps failing. We logged in to the account on each occasion (without using switch role from the master account) and there was explicit deny to all IAM resources. Not able to create users or groups or roles in the developer account, not able to deploy any VM. SCP locks everything down. May we get support on what to do in this scenario in order to gain access to configure the dev or other workload environment? What changes do we make to the config file that will allow us to use the environment? What changes do we need to make in the master account that will help?

**Failure Info**
- What error messages have you identified, if any: 
- 
<img width="1000" alt="SCP" src="https://user-images.githubusercontent.com/78378245/110155081-54741600-7da2-11eb-94b4-f905ec879b16.png">
![Switch Role error](https://user-images.githubusercontent.com/78378245/110155455-de23e380-7da2-11eb-8531-d9892bcfa673.jpg)

- What symptoms have you identified, if any:

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. Go to '...'  log in as admin in master account, 
2. Click on '....' choose your user name on the navigation bar in the upper right, 
3. See error choose switch roles and then switch role to developer account

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by archikierstead** [comment]
Hi,

You need to go through the post-installation steps (Section 2.6) of the Installation Doc: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/installation/installation.md

You should enable SSO and use SSO to login to your sub-accounts.

The SCP controls you mention are by design to meet the security control requirements.

**Comment by Geebhawllar** [comment]
Thank you James for this quick response, appreciate it
 
I have done all post installation steps in the link except for 1
 
I enabled MFA for master account, but we cannot enable MFA for child account due to the fact that SCP policies at the Dev OU level is restricting any changes to account of members.
 
Can this be a hard blocker? 
 
I will use SSO to sign in, AWS SSO with MAD is already configured
 
Thanks James for your response
Bola Olaniyi
AWS Application Architect
 
Mobile: 1-403-891-2865E-mail: bola.olaniyi@ibm.com
227 - 11th Avenue SwCalgary, AB T2R 1R9Canada
 
 
 
----- Original message -----From: James Kierstead <notifications@github.com>To: aws-samples/aws-secure-environment-accelerator <aws-secure-environment-accelerator@noreply.github.com>Cc: Geebhawllar <Bola.Olaniyi@ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [aws-samples/aws-secure-environment-accelerator] SCP not allowing configuration of development environment (#655)Date: Fri, Mar 5, 2021 4:06 PM  
 
Hi,
You need to go through the post-installation steps (Section 2.6) of the Installation Doc: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/installation/installation.md
You should enable SSO and use SSO to login to your sub-accounts.
The SCP controls you mention are by design to meet the security control requirements.

**Comment by Geebhawllar** [comment]
Thanks james, 
 
I am logged in to the dev account
 
Enjoy your weekend
Bola Olaniyi
AWS Application Architect
 
Mobile: 1-403-891-2865E-mail: bola.olaniyi@ibm.com
227 - 11th Avenue SwCalgary, AB T2R 1R9Canada
 
 
 
----- Original message -----From: James Kierstead <notifications@github.com>To: aws-samples/aws-secure-environment-accelerator <aws-secure-environment-accelerator@noreply.github.com>Cc: Geebhawllar <Bola.Olaniyi@ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [aws-samples/aws-secure-environment-accelerator] SCP not allowing configuration of development environment (#655)Date: Fri, Mar 5, 2021 4:06 PM  
 
Hi,
You need to go through the post-installation steps (Section 2.6) of the Installation Doc: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/installation/installation.md
You should enable SSO and use SSO to login to your sub-accounts.
The SCP controls you mention are by design to meet the security control requirements.
