### ISSUE TITLE
[BUG][Functional] Uninstall Script fails: organization-admin-role doesn't have permission to ListStacks outside of the 'approved' regions

### ISSUE THREAD

**Issue by BrianFanning** [aws-samples/aws-secure-environment-accelerator#760]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.2.4
- Install Type: Upgrade
- Upgrade from version: v1.2.3
- Which State did the Main State Machine Fail in: NA

**Describe the bug**
The cleanup script uses the organization-admin-role (in my case, AWSCloudFormationStackSetExecutionRole) to delete the CFN stacks, but that role doesn't have permission to ListStacks in any region which isn't the home region (e.g. ap-northeast-1), so the cleanup scripts fail

**Failure Info**
Output from my cleanup script:
`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListStacks operation: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/AWSCloudFormationStackSetExecutionRole/AcceleratorCleanupScript is not authorized to perform: cloudformation:ListStacks on resource: arn:aws:cloudformation:ap-northeast-1:xxxxxxxxxxxx:stack/*/* with an explicit deny`

**Steps To Reproduce**
Run the cleanup script from the command line

**Expected behavior**
All ASEA-related stacks should be deleted

**Comment by Brian969** [comment]
Hey Brian,
- This is an unsupported internal script, meant for internal use only, if it's broken, love it if you could contribute a fix.  It should be easy (i.e. change to always using {AcceleratorPrefix}-PipelineRole), instead of reading from config file;
- the OrgAdmin role was only moved within the governance structure in v1.2.5, so you should not be having this issue in v1.2.4 (assuming this was a typo);
- As a workaround, turn off SCP remediation and then disconnect the SCP's from all ASEA OU's before running the script;

BTW: I'm a little surprised nobody else has encountered/reported this issue, as it is used regularly

**Comment by Brian969** [comment]
@rjjaegeraws - is this an issue or simply requires documentation updates?

**Comment by rjjaegeraws** [comment]
> 

I don't believe this is an issue any more with an update I made at the end of October. ([here](https://github.com/aws-samples/aws-secure-environment-accelerator/commit/12b95fee7d87466b53e6662773d58dbd1ced2189)).

This update moved the `delete_scp` to an initial step (i.e. implementing your 3rd bullet point above). This can be seen on line #498 in the latest version of the uninstall script.
